dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

matrix:
  include:
    - name: "All"
      env:
      - TARGET=all
    
    - name: "String"
      env: 
      - TARGET=String
    
    - name: "Functions"
      env:
      - TARGET=functions RECURSIVE=true
      - TARGET=functions RECURSIVE=false
    
    - name: "Sorts"
      env:
      - TARGET=bubble
      - TARGET=insertion
      - TARGET=selection
      - TARGET=merge
      - TARGET=quick
      - TARGET=tree
      - TARGET=hybrid
    
    - name: "Lists"
      env:
      - TARGET=SLL
      - TARGET=CSLL
      - TARGET=DLL
      - TARGET=CDLL
    
    - name: "Trees"
      env:
      - TARGET=BST
      - TARGET=RBTree
      - TARGET=Trie
    
    - name: "Algorithms"
      env:
      - TARGET=twostack

script:
  - make $TARGET